package rs.ftn.newnow.model.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTERED,
    ACCOUNT_APPROVED,
    ACCOUNT_REJECTED,
    LOCATION_CREATED,
    LOCATION_UPDATED,
    LOCATION_DELETED,
    LOCATION_IMAGE_UPDATED,
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_DELETED,
    EVENT_IMAGE_UPDATED,
    MANAGER_ASSIGNED,
    MANAGER_REMOVED,
    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_DELETED,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,
    AVATAR_UPDATED
}
